# @format

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: zhangchi-0104-blog
      match:
        path:
          prefix: /
name: monkfish-app
region: syd
services:
  - envs:
      - key: DATABASE_TRANSACTION_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DATABASE_TRANSACTION_URL}
        type: SECRET
      - key: DATABASE_DIRECT_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DATABASE_DIRECT_URL}
        type: SECRET
    http_port: 8000
    image:
      registry: zhangchi0104
      registry_type: DOCKER_HUB
      repository: blog
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: zhangchi-0104-blog
