# @format

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
domains:
  - domain: prod.api.chiz.dev
    type: PRIMARY
ingress:
  rules:
    - component:
        name: zhangchi-0104-blog
      match:
        path:
          prefix: /v1
name: monkfish-app
region: syd
services:
  - envs:
      - key: DATABASE_TRANSACTION_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DATABASE_TRANSACTION_URL}
        type: SECRET
      - key: DATABASE_DIRECT_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DATABASE_DIRECT_URL}
        type: SECRET
      - key: BUCKET_ENDPOINT
        scope: RUN_TIME
        value: ${BUCKET_ENDPOINT}
        type: SECRET
      - key: BUCKET_REGION
        scope: RUN_TIME
        value: ${BUCKET_REGION}
      - key: BUCKET_ACCESS_KEY_ID
        scope: RUN_TIME
        value: ${BUCKET_ACCESS_KEY_ID}
        type: SECRET
      - key: BUCKET_SECRET_ACCESS_KEY
        scope: RUN_TIME
        value: ${BUCKET_SECRET_ACCESS_KEY}
        type: SECRET
      - key: SUPABASE_URL
        scope: RUN_TIME
        value: ${SUPABASE_URL}
        type: SECRET
      - key: SUPABASE_ANON_KEY
        scope: RUN_TIME
        value: ${SUPABASE_ANON_KEY}
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        value: ${SUPABASE_SERVICE_ROLE_KEY}
        type: SECRET
      - key: SUPABASE_JWT_SECRET
        scope: RUN_TIME
        value: ${SUPABASE_JWT_SECRET}
        type: SECRET
      - key: BLOG_ASSETS_BUCKET
        scope: RUN_TIME
        value: ${BLOG_ASSETS_BUCKET}
      - key: BLOG_CONTENT_BUCKET
        scope: RUN_TIME
        value: ${BLOG_CONTENT_BUCKET}
    http_port: 8000
    image:
      registry: zhangchi0104
      registry_type: DOCKER_HUB
      repository: blog
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: zhangchi-0104-blog
