# @format

name: Build backend

on:
  push:
    paths:
      - "apps/kuma-elysia/**"
    branches:
      - main
  workflow_dispatch:
jobs:
  db-migration:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Apply all pending migrations to the database
        run: bunx turbo db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_TRANSACTION_URL }}

  build-and-push:
    needs: db-migration
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/blog:latest
          file: apps/kuma-elysia/Dockerfile

    outputs:
      image_digest: ${{ steps.push.outputs.digest }}

  deploy:
    needs: build-and-push
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
        env:
          BUCKET_PROVIDER: supabase
          BLOG_ASSETS_BUCKET: ${{ vars.BLOG_ASSETS_BUCKET }}
          BLOG_CONTENT_BUCKET: ${{ vars.BLOG_CONTENT_BUCKET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_DIRECT_URL }}
