# @format

name: Database schema migration
on:
  push:
    paths:
      - apps/kuma-elysia/prisma/migrations/** # Only run this workflow when migrations are updated
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/database

jobs:
  deploy:
    environment: 'prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Apply all pending migrations to the database
        run: bunx prisma migrate deploy
        env:
          DATABASE_TRANSACTION_URL: ${{ secrets.DATABASE_TRANSACTION_URL }}
          DATABASE_DIRECT_URL: ${{ secrets.DATABASE_DIRECT_URL }}
